### ISSUE TITLE
Network requests do not work in Simulator

### ISSUE THREAD

**Issue by dcamenisch** [adamayoung/TMDb#125]
Network requests do not seem to work in the Simulator and only on an actual device. The following code was used:

```swift
return try await trendingService.tvSeries(inTimeWindow: .week, page: page).results
``` 

The call never returns.

This behavior was observed with the newest version of TMDb (bb032f0) and iOS 17.0 (both on device and in the Simulator).

**Comment by dcamenisch** [comment]
Seemed to be a issue related to the simulator. After reinstalling the app and restarting the simulator it worked.

**Comment by yood** [comment]
Happened to me just now. Re-install in simulator fixed it.

**Comment by movesmyers** [comment]
@yood can you clarify how you passed in your own client? I'm having this same issue and I'm having trouble with figuring out the fix.
