### ISSUE TITLE
Question: how to fetch favorite movies

### ISSUE THREAD

**Issue by buhe** [adamayoung/TMDb#154]
Hey
Nice project!
But i have a question. Such as https://developer.themoviedb.org/reference/account-get-favorites

**Describe the bug**
How to fetch favorite movies

Thanks.

**Comment by adamayoung** [comment]
Hey @buhe . Thanks for the feedback.

I haven't implemented any of the account endpoints as of yet. I'll have a look at doing this in the near future.

**Comment by buhe** [comment]
Thanks.
