### ISSUE TITLE
Conform value types to Sendable

### ISSUE THREAD

**Issue by MartinP7r** [adamayoung/TMDb#167]
I see these warnings when using the `async` APIs and was wondering if the fix would be as simple as adding conformance to `Sendable` for the types in question?

<img width="880" alt="image" src="https://github.com/adamayoung/TMDb/assets/2669027/c3b07555-bc77-413f-82a3-6df985e677d5">

Disclaimer: this is with `StrictConcurrency` option activated, so most likely won't show up by default right now.

**Comment by adamayoung** [comment]
Hi @MartinP7r. Thanks for the issue. I'll look at sending this sorted ASAP.
