### ISSUE TITLE
Feature Request: Aggregate Credits support

### ISSUE THREAD

**Issue by barfoon** [adamayoung/TMDb#172]
Awesome library! I'd love to be able to pull from `https://api.themoviedb.org/3/tv/{series_id}/aggregate_credits
` with this client

e.g `Game of Thrones` series ID: `1399` returns only 14 cast members:
https://gist.github.com/barfoon/387c5333e7176e88800363088e11008b

where `aggregate_credits` returns much more:
https://gist.github.com/barfoon/cb9e6eb4f3df45a76a40d77ea6ab9882

Thanks!

**Comment by adamayoung** [comment]
Hey @barfoon . Thanks for the feedback!

I didn't even know this endpoint existed, and did wonder my the credits contain so few people. Will look at getting it added.

**Comment by barfoon** [comment]
Thanks @adamayoung !

**Comment by barfoon** [comment]
Appreciate you jumping on this

Any idea on when it will be released @adamayoung ?

**Comment by adamayoung** [comment]
@barfoon Apologies for the delay. Was hoping to get something else in before doing another release.

`12.1.0` is now available with this change 🚀

**Comment by barfoon** [comment]
Badass 👍
