### ISSUE TITLE
Do you support getting the streaming providers for a particular show or a movie?

### ISSUE THREAD

**Issue by artangco** [adamayoung/TMDb#86]
Do you support getting the streaming providers for a particular show or a movie?
I think TMDB has that api. wondering if you support it and if so how can I get to it?

Much appreciate the work you are doing.

**Comment by adamayoung** [comment]
Hey @artangco.

There's the `WatchProviderService` on TMDbAPI. e.g.

```swift
let tmdb = TMDbAPI(apiKey: "abc123")

let movieWatchProviders = try await tmdbs.watchProviders.movieWatchProviders()

let tvShowWatchProviders = try await tmdbs.watchProviders.tvShowWatchProviders()
```

Is that what you mean?


And thanks for the kind words 🙏🏻
