### ISSUE TITLE
Enhancement: make some structs (like TVShow, Movie and Show enum) conform to Encodable and Codable protocols

### ISSUE THREAD

**Issue by thepantalion** [adamayoung/TMDb#87]
a basic implementation might be to just encode only the basic needed data, like id and: title for a movie, name for a show
then retrieve other needed data with a manual call to the methods that talk to TMDb

thanks~

**Comment by adamayoung** [comment]
Hi @thepantalion. Thanks for using my TMDb Swift Package 🙏🏻

If you take a look at the main branch you'll see all models conform to `Codable`.
