### ISSUE TITLE
iOS 13 Support

### ISSUE THREAD

**Issue by matheuslutero** [adamayoung/TMDb#92]
Hi there,

I hope you're doing well. I wanted to let you know that while using your library, I encountered a compatibility issue. Currently, the library only supports iOS 15 and above, but my project requires a minimum iOS version of 13. To address this, I forked the repository and made the necessary change to `Package.swift` to enable compatibility with iOS 13. All tests have passed successfully, and the library is working flawlessly.

I believe it would greatly benefit the community if the library could support iOS 13 and higher. I would be grateful if you could consider incorporating this change into the main repository.

**Comment by adamayoung** [comment]
Hey @matheuslutero. Thanks for using my TMDb Swift package 🙏🏻

I've just made a recent change on the main branch which changes the minimum iOS version to 13. I haven't made a release yet, but you can use the main branch till I do.
